// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FileInputController from "./file_input_controller"
application.register("file-input", FileInputController)

import IngredientController from "./ingredient_controller"
application.register("ingredient", IngredientController)

import MealController from "./meal_controller"
application.register("meal", MealController)
